import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/src/styles/globals.css';
import { Nav } from '@/src/components';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <Nav />
      <main>{children}</main>
    </body>
  </html>
);

export default RootLayout;
